export async function GET({request,response}) {
  // Some code...
}
export async function POST({request,response}) {
  // Some code...
}
export async function DELETE({request,response}) {
  // Some code...
}
export async function PATCH({request,response}) {
  // Some code...
}
